/**
 * ART QR STYLE SYSTEM — the 50 art directions.
 *
 * Global rules this file is responsible for:
 *
 *   1. QR structural integrity — directions never touch the matrix, they only
 *      describe how it is painted (see art-plan.ts).
 *   2. Camera scanability — every direction ships a `cameraSafe` fallback and
 *      per-level-of-detail tweaks driven by pixelsPerModule.
 *   3. Finder-pattern detection — finder styles keep the 1:1:3:1:1 ratio.
 *   4. Quiet-zone preservation — `quietZone >= 3` and the plan clips to the body.
 *   5. Aggregate dark/light separation — `resolveInks` measures *luminance*,
 *      never assumes "red vs blue = contrast", and repairs any ramp that fails.
 *   6. Visual beauty — each direction varies shape + geometry + distortion +
 *      gradient + finder + accent, so the gallery reads as 50 design systems
 *      rather than 50 colour swaps.
 */

import type {
  ArtDetailLevel,
  ArtDirection,
  ArtLodTweaks,
  Preset,
  QrStyle,
} from "./types";
import { DEFAULT_STYLE } from "./types";

/* ------------------------------------------------------------------ *
 * Colour math — the COLOR RULE
 * ------------------------------------------------------------------ */

export function hexToRgb(hex: string): [number, number, number] {
  const m = /^#?([0-9a-f]{6})$/i.exec(hex.trim());
  if (!m) return [17, 17, 17];
  const n = parseInt(m[1]!, 16);
  return [(n >> 16) & 255, (n >> 8) & 255, n & 255];
}

export function rgbToHex(rgb: [number, number, number]): string {
  const c = (v: number) => Math.max(0, Math.min(255, Math.round(v))).toString(16).padStart(2, "0");
  return `#${c(rgb[0])}${c(rgb[1])}${c(rgb[2])}`;
}

export function lumaOf(hex: string): number {
  const [r, g, b] = hexToRgb(hex);
  return (0.2126 * r + 0.7152 * g + 0.0722 * b) / 255;
}

function rgbToHsl([r, g, b]: [number, number, number]): [number, number, number] {
  const rn = r / 255;
  const gn = g / 255;
  const bn = b / 255;
  const max = Math.max(rn, gn, bn);
  const min = Math.min(rn, gn, bn);
  const l = (max + min) / 2;
  const d = max - min;
  if (d === 0) return [0, 0, l];
  const s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
  let h: number;
  if (max === rn) h = ((gn - bn) / d + (gn < bn ? 6 : 0)) / 6;
  else if (max === gn) h = ((bn - rn) / d + 2) / 6;
  else h = ((rn - gn) / d + 4) / 6;
  return [h, s, l];
}

function hslToRgb([h, s, l]: [number, number, number]): [number, number, number] {
  if (s === 0) {
    const v = Math.round(l * 255);
    return [v, v, v];
  }
  const q = l < 0.5 ? l * (1 + s) : l + s - l * s;
  const p = 2 * l - q;
  const ch = (tRaw: number) => {
    let t = tRaw;
    if (t < 0) t += 1;
    if (t > 1) t -= 1;
    if (t < 1 / 6) return p + (q - p) * 6 * t;
    if (t < 1 / 2) return q;
    if (t < 2 / 3) return p + (q - p) * (2 / 3 - t) * 6;
    return p;
  };
  return [
    Math.round(ch(h + 1 / 3) * 255),
    Math.round(ch(h) * 255),
    Math.round(ch(h - 1 / 3) * 255),
  ];
}

/** Move a colour's luminance to `target` while keeping its hue and chroma. */
export function setLuma(hex: string, target: number): string {
  const hsl = rgbToHsl(hexToRgb(hex));
  const t = Math.max(0, Math.min(1, target));
  // Luminance and HSL lightness are not the same curve, but two Newton steps
  // on L land within ~0.01 of the target while preserving hue.
  let l = hsl[2];
  for (let i = 0; i < 4; i++) {
    const got = lumaOf(rgbToHex(hslToRgb([hsl[0], hsl[1], l])));
    const err = t - got;
    if (Math.abs(err) < 0.004) break;
    l = Math.max(0, Math.min(1, l + err * 0.85));
  }
  return rgbToHex(hslToRgb([hsl[0], hsl[1], l]));
}

/** Darken toward `target` only if currently above it (hue-preserving). */
function atMostLuma(hex: string, target: number): string {
  return lumaOf(hex) <= target ? hex : setLuma(hex, target);
}

/** Lighten toward `target` only if currently below it. */
function atLeastLuma(hex: string, target: number): string {
  return lumaOf(hex) >= target ? hex : setLuma(hex, target);
}

/* ------------------------------------------------------------------ *
 * Ink resolution — verifies (and repairs) luminance separation
 * ------------------------------------------------------------------ */

/** Aggregate dark/light separation the decoder needs. jsQR is tolerant, but
 *  the camera battery (blur + 50% downscale + JPEG) is not. */
export const MIN_SEPARATION = 0.46;
/** Accent ink may never be mistaken for the opposite polarity. */
export const MAX_ACCENT_CONFUSION = 0.14;
/** Light-cell decoration must stay within this luminance of the paper —
 *  jsQR's block binariser turns anything further away into phantom modules. */
export const MAX_LIGHT_ACCENT_DELTA = 0.09;

export interface ResolvedInks {
  stops: string[];
  bg: string;
  eye: string;
  ball: string;
  accent: string | null;
  /** Measured separation between ink ramp and paper. */
  separation: number;
  /** True when the paper is the bright side (normal polarity). */
  normalPolarity: boolean;
  /** Which colours the gate had to move, and why. */
  repairs: string[];
}

/**
 * The COLOR RULE, enforced. Measures effective luminance of every ink against
 * the paper and repairs ramps that would render as "two visually different
 * colours with the same luminance". Hue is preserved; only lightness moves.
 */
export function resolveInks(dir: ArtDirection): ResolvedInks {
  const repairs: string[] = [];
  const min = dir.minSeparation ?? MIN_SEPARATION;
  const bg = dir.bg;
  const bgL = lumaOf(bg);
  const normalPolarity = bgL > 0.5;

  // Ink must live on the opposite side of the paper, with the worst (closest)
  // stop still `min` away from it.
  const inkTarget = normalPolarity ? bgL - min : bgL + min;
  const clampInk = (hex: string, label: string): string => {
    const l = lumaOf(hex);
    const sep = Math.abs(l - bgL);
    if (sep >= min) return hex;
    const fixed = normalPolarity ? atMostLuma(hex, inkTarget) : atLeastLuma(hex, inkTarget);
    repairs.push(`${label} lifted from ${sep.toFixed(2)} to ${min.toFixed(2)} separation`);
    return fixed;
  };

  const stops = dir.stops.map((s, i) => clampInk(s, i === 0 ? "ink" : `ink stop ${i + 1}`));
  const ramp = dir.ramp?.map((s, i) => clampInk(s, `ramp ${i + 1}`));
  const eye = clampInk(dir.eye ?? stops[0]!, "finder");
  const ball = clampInk(dir.ball ?? stops[0]!, "finder ball");

  // Accents are decorative: they must read as the polarity they sit on.
  // Accents always sit ON dark modules, luminance-locked to the ink. A mark on
  // a *light* cell becomes a phantom module under jsQR's local min-max
  // binarisation no matter how pale it is, so the system refuses to paint one.
  let accent: string | null = null;
  if (dir.accent) {
    const aL = lumaOf(dir.accent);
    const inkL = lumaOf(stops[0]!);
    if (Math.abs(aL - inkL) > MAX_ACCENT_CONFUSION) {
      accent = setLuma(dir.accent, inkL + (aL > inkL ? MAX_ACCENT_CONFUSION : -MAX_ACCENT_CONFUSION));
      repairs.push("accent pulled back into the ink band");
    } else accent = dir.accent;
  }

  const all = [...stops, ...(ramp ?? []), eye, ball];
  const worst = all.reduce((acc, c) => Math.min(acc, Math.abs(lumaOf(c) - bgL)), 1);

  return {
    stops,
    bg,
    eye,
    ball,
    accent,
    separation: worst,
    normalPolarity,
    repairs,
  };
}

/* ------------------------------------------------------------------ *
 * pixelsPerModule — the LOD contract
 * ------------------------------------------------------------------ */

export interface ArtViewport {
  /** finalRenderedPixels / QRModuleCount, including the quiet zone in the frame. */
  ppm: number;
  /** Module count of the encoded matrix. */
  modules: number;
}

export function detailLevelFor(ppm: number): ArtDetailLevel {
  if (ppm >= 10) return "rich";
  if (ppm >= 5.5) return "standard";
  return "lean";
}

export function ppmOf(px: number, modules: number, quietZone: number): number {
  const total = modules + 2 * quietZone;
  return total > 0 ? px / total : 0;
}

/**
 * Resolve a direction to the geometry it should actually paint at this size.
 * Small modules ⇒ simplify shapes, drop fine decoration, enlarge features,
 * raise luminance contrast, reduce texture — while keeping the identity.
 */
export function resolveDirection(
  dir: ArtDirection,
  level: ArtDetailLevel,
  opts: { cameraSafe?: boolean } = {},
): ArtDirection {
  const tweaks: ArtLodTweaks = {
    ...(dir.lod?.[level] ?? {}),
    ...(opts.cameraSafe ? (dir.cameraSafe ?? {}) : {}),
  };
  return {
    ...dir,
    shape: tweaks.shape ?? dir.shape,
    radius: tweaks.radius ?? dir.radius,
    geometry: tweaks.geometry ?? dir.geometry,
    distortion: tweaks.distortion ?? dir.distortion,
    gradient: tweaks.gradient ?? dir.gradient,
    accentMark: tweaks.accent ?? dir.accentMark,
    gap: tweaks.gap ?? dir.gap,
    mass: tweaks.mass ?? dir.mass,
    minSeparation:
      tweaks.contrastBoost !== undefined
        ? (dir.minSeparation ?? MIN_SEPARATION) + tweaks.contrastBoost
        : dir.minSeparation,
  };
}

/* ------------------------------------------------------------------ *
 * Module mass — the SHAPE RULE
 * ------------------------------------------------------------------ */

/**
 * Filled-area ratio of each shape at scale 1 (fraction of the module box).
 * A dark module must never become a tiny decorative dot, so the renderer
 * scales low-mass shapes up until they carry enough ink.
 */
export const SHAPE_COVERAGE: Record<string, number> = {
  square: 1,
  rounded: 0.93,
  squircle: 0.86,
  dots: 0.73,
  capsule: 0.79,
  pill: 0.79,
  diamond: 0.5,
  hex: 0.68,
  star: 0.34,
  plus: 0.52,
  leaf: 0.72,
  petal: 0.66,
  heart: 0.64,
  pebble: 0.84,
  gem: 0.6,
  facet: 0.57,
  classy: 0.86,
  fluid: 0.94,
  confetti: 0.37,
  dash: 0.42,
  cross: 0.3,
  diag: 0.36,
  radial: 0.34,
  bubbles: 0.36,
  hbar: 0.46,
  vbar: 0.46,
};

/** Filled-area floor for a dark data module. Below this the camera battery fails. */
export const MIN_DARK_MASS = 0.78;
/** Ceiling — above this neighbouring modules visually merge into blobs. */
export const MAX_DARK_MASS = 1.0;
/** Light-cell decoration may never exceed this fraction of the cell. */
export const MAX_LIGHT_MARK = 0.16;

export function coverageOf(shape: string): number {
  return SHAPE_COVERAGE[shape] ?? 0.8;
}

/** Scale multiplier that brings `shape` up to `targetMass` of the module box. */
export function massScale(shape: string, targetMass: number, gap: number): number {
  const cov = coverageOf(shape) * Math.max(0.4, 1 - gap);
  const scale = Math.sqrt(targetMass / cov);
  return Math.max(0.85, Math.min(1.7, scale));
}

/* ------------------------------------------------------------------ *
 * The 50 directions
 * ------------------------------------------------------------------ */

type ArtDirectionSpec = Omit<
  ArtDirection,
  "strength" | "accentFreq" | "quietZone" | "alignment" | "minSeparation"
> &
  Partial<Pick<ArtDirection, "strength" | "accentFreq" | "quietZone" | "alignment" | "minSeparation">>;

function d(spec: ArtDirectionSpec): ArtDirection {
  return {
    ...spec,
    strength: spec.strength ?? 0.6,
    accentFreq: spec.accentFreq ?? 0,
    quietZone: spec.quietZone ?? 3,
    alignment: spec.alignment ?? "solid",
    minSeparation: spec.minSeparation ?? MIN_SEPARATION,
    lod: {
      // Camera-safe simplification ladder, per direction unless overridden.
      lean: {
        geometry: spec.geometry === "traces" ? "runs-both" : spec.geometry,
        distortion: "none",
        accent: "none",
        gap: Math.min(spec.gap, 0.03),
        mass: Math.max(spec.mass, 0.88),
        contrastBoost: 0.04,
        ...(spec.lod?.lean ?? {}),
      },
      standard: {
        distortion: spec.distortion === "jitter" ? "none" : spec.distortion,
        ...(spec.lod?.standard ?? {}),
      },
    },
    cameraSafe: {
      geometry: "single",
      distortion: "none",
      accent: "none",
      gradient: spec.gradient === "bands" || spec.gradient === "spectrum" ? "linear-y" : spec.gradient,
      shape:
        coverageOf(spec.shape) < 0.6
          ? "rounded"
          : spec.shape === "hbar" || spec.shape === "vbar"
            ? "rounded"
            : spec.shape,
      radius: Math.min(spec.radius, 0.34),
      gap: 0,
      mass: 0.95,
      contrastBoost: 0.06,
      ...(spec.cameraSafe ?? {}),
    },
  };
}

export const ART_DIRECTIONS: ArtDirection[] = [
  /* ---------------- Neon ---------------- */
  d({
    id: "neon-cyber-grid",
    name: "Neon Cyber Grid",
    category: "Neon",
    blurb: "Electric cyan→magenta grid traces on black, bold cyan finders.",
    stops: ["#22e6ff", "#b45cff"],
    ramp: ["#22e6ff", "#ff3df0", "#8a5cff"],
    bg: "#04060d",
    eye: "#39f2ff",
    ball: "#eafcff",
    shape: "squircle",
    radius: 0.3,
    geometry: "traces",
    distortion: "steps",
    gradient: "spectrum",
    finder: "ring8",
    timing: "solid",
    alignment: "solid",
    accentMark: "tick",
    accent: "#ff3df0",
    accentFreq: 0.1,
    mass: 0.92,
    gap: 0.06,
    strength: 0.72,
  }),
  d({
    id: "aurora-gradient",
    name: "Aurora Gradient",
    category: "Neon",
    blurb: "Emerald → cyan → violet → pink curtain, rounded modules.",
    stops: ["#2ee6a8", "#a45cff"],
    ramp: ["#2ee6a8", "#31d8f0", "#9a63ff", "#ff77d2"],
    bg: "#050b16",
    eye: "#7ef7d8",
    ball: "#eafff8",
    shape: "rounded",
    radius: 0.34,
    geometry: "components",
    distortion: "wobble",
    gradient: "linear-y",
    finder: "circle",
    timing: "pill",
    alignment: "pill",
    accentMark: "none",
    mass: 0.9,
    gap: 0.05,
    strength: 0.7,
  }),
  d({
    id: "liquid-chrome",
    name: "Liquid Chrome",
    category: "Neon",
    blurb: "Polished silver modules with highlight bands on charcoal.",
    stops: ["#f0f3f7", "#9aa4b2"],
    ramp: ["#ffffff", "#c9d2dd", "#8d97a5"],
    bg: "#15181c",
    eye: "#f4f7fa",
    ball: "#dfe6ee",
    shape: "squircle",
    radius: 0.38,
    geometry: "runs-h",
    distortion: "bands",
    gradient: "bands",
    finder: "ring8",
    timing: "solid",
    alignment: "solid",
    accentMark: "none",
    mass: 0.94,
    gap: 0.04,
    strength: 0.6,
  }),
  d({
    id: "sunset-spectrum",
    name: "Sunset Spectrum",
    category: "Neon",
    blurb: "Orange → coral → pink → purple, flowing capsule modules.",
    stops: ["#ffb03a", "#c04bd6"],
    ramp: ["#ffc247", "#ff7a59", "#ff5fa2", "#a44fe0"],
    bg: "#170a1c",
    eye: "#ffd08a",
    ball: "#fff0d6",
    shape: "capsule",
    radius: 0.5,
    geometry: "runs-h",
    distortion: "taper",
    gradient: "diagonal",
    finder: "ring8",
    timing: "pill",
    alignment: "pill",
    accentMark: "none",
    mass: 0.9,
    gap: 0.05,
    strength: 0.68,
  }),
  d({
    id: "ocean-glass",
    name: "Ocean Glass",
    category: "Neon",
    blurb: "Turquoise glass capsules clustered on deep navy.",
    stops: ["#5ff0e0", "#2f9fe0"],
    ramp: ["#8ff8ec", "#47cfe8", "#2f7fd6"],
    bg: "#061a2c",
    eye: "#9df6ee",
    ball: "#e6fffb",
    shape: "capsule",
    radius: 0.46,
    geometry: "components",
    distortion: "wobble",
    gradient: "radial",
    finder: "soft",
    timing: "pill",
    alignment: "ring",
    accentMark: "none",
    mass: 0.9,
    gap: 0.05,
    strength: 0.66,
  }),
  d({
    id: "emerald-luxury",
    name: "Emerald Luxury",
    category: "Neon",
    blurb: "Emerald modules on near-black with restrained gold flecks.",
    stops: ["#19d67f", "#0f8f56"],
    bg: "#030a07",
    eye: "#2bf096",
    ball: "#d9ffe9",
    accent: "#e9c46a",
    shape: "rounded",
    radius: 0.24,
    geometry: "single",
    distortion: "none",
    gradient: "linear-y",
    finder: "solid",
    timing: "solid",
    alignment: "solid",
    accentMark: "fleck",
    accentFreq: 0.09,
    mass: 0.95,
    gap: 0.04,
    strength: 0.55,
  }),
  d({
    id: "cyberpunk-pink",
    name: "Cyberpunk Pink",
    category: "Neon",
    blurb: "Hot-pink bars on black, cyan bracket finders, violet accents.",
    stops: ["#ff3d95", "#b02fd6"],
    bg: "#08040c",
    eye: "#3ef2ff",
    ball: "#e6fdff",
    accent: "#8a5cff",
    shape: "hbar",
    radius: 0.3,
    geometry: "runs-h",
    distortion: "steps",
    gradient: "split",
    finder: "bracket",
    timing: "solid",
    alignment: "solid",
    accentMark: "tick",
    accentFreq: 0.12,
    mass: 0.92,
    gap: 0.05,
    strength: 0.74,
  }),
  d({
    id: "electric-blue",
    name: "Electric Blue",
    category: "Neon",
    blurb: "Saturated cobalt on white — square and soft modules in rhythm.",
    stops: ["#0b4fe0", "#1877ff"],
    bg: "#ffffff",
    eye: "#08307f",
    ball: "#08307f",
    shape: "rounded",
    radius: 0.18,
    geometry: "runs-both",
    distortion: "jitter",
    gradient: "linear-x",
    finder: "solid",
    timing: "solid",
    alignment: "solid",
    accentMark: "none",
    mass: 0.96,
    gap: 0.03,
    strength: 0.5,
    lod: { lean: { geometry: "single", distortion: "none" } },
  }),
  d({
    id: "solar-flare",
    name: "Solar Flare",
    category: "Neon",
    blurb: "Yellow → orange → red flame rhythm in large module groups.",
    stops: ["#ffd23f", "#ff3b1f"],
    ramp: ["#ffe066", "#ff9f1c", "#ff4d1c", "#d61f2b"],
    bg: "#180403",
    eye: "#ffb703",
    ball: "#fff3c4",
    shape: "fluid",
    radius: 0.42,
    geometry: "components",
    distortion: "taper",
    gradient: "radial",
    finder: "solid",
    timing: "pill",
    alignment: "solid",
    accentMark: "spark",
    accent: "#ffe066",
    accentFreq: 0.07,
    mass: 0.92,
    gap: 0.04,
    strength: 0.72,
  }),
  d({
    id: "vaporwave",
    name: "Vaporwave",
    category: "Neon",
    blurb: "Purple/pink/cyan bands with rounded geometric modules.",
    stops: ["#ff8ad4", "#7b5cff"],
    ramp: ["#5ff0e6", "#ff8ad4", "#9d6bff"],
    bg: "#120a24",
    eye: "#5ff0e6",
    ball: "#f4e9ff",
    shape: "squircle",
    radius: 0.36,
    geometry: "runs-h",
    distortion: "bands",
    gradient: "bands",
    finder: "circle",
    timing: "pill",
    alignment: "pill",
    accentMark: "none",
    mass: 0.92,
    gap: 0.05,
    strength: 0.68,
  }),
  d({
    id: "synthwave-sunset",
    name: "Synthwave Sunset",
    category: "Neon",
    blurb: "Orange/pink horizon modules on deep purple, immaculate finders.",
    stops: ["#ff9e3d", "#ff4f9a"],
    ramp: ["#ffd166", "#ff6b6b", "#ff4f9a"],
    bg: "#160a2b",
    eye: "#ffd166",
    ball: "#fff1d6",
    shape: "hbar",
    radius: 0.34,
    geometry: "runs-h",
    distortion: "bands",
    gradient: "linear-y",
    finder: "solid",
    timing: "solid",
    alignment: "solid",
    accentMark: "none",
    mass: 0.93,
    gap: 0.04,
    strength: 0.66,
  }),
  d({
    id: "cyber-circuit",
    name: "Cyber Circuit",
    category: "Neon",
    blurb: "Board traces: rectangular runs joined at right angles.",
    stops: ["#37e0a4", "#1fa97c"],
    bg: "#04120d",
    eye: "#5cf0bd",
    ball: "#d6fff0",
    accent: "#c9f25c",
    shape: "square",
    radius: 0.06,
    geometry: "traces",
    distortion: "none",
    gradient: "linear-y",
    finder: "circuit",
    timing: "solid",
    alignment: "solid",
    accentMark: "tick",
    accentFreq: 0.08,
    mass: 0.95,
    gap: 0.07,
    strength: 0.62,
  }),
  d({
    id: "digital-matrix",
    name: "Digital Matrix",
    category: "Neon",
    blurb: "Falling-code vertical runs in green shades on black.",
    stops: ["#4dff88", "#0fa648"],
    ramp: ["#c8ffd8", "#4dff88", "#12a44c"],
    bg: "#010803",
    eye: "#7dff9f",
    ball: "#e8ffe9",
    shape: "vbar",
    radius: 0.14,
    geometry: "runs-v",
    distortion: "steps",
    gradient: "linear-y",
    finder: "bracket",
    timing: "solid",
    alignment: "solid",
    accentMark: "fleck",
    accent: "#d8ffe2",
    accentFreq: 0.06,
    mass: 0.92,
    gap: 0.06,
    strength: 0.7,
  }),
  d({
    id: "holographic",
    name: "Holographic",
    category: "Neon",
    blurb: "Cyan→blue→purple→pink by position, clean gem geometry.",
    stops: ["#5ff0ff", "#c05cff"],
    ramp: ["#5ff0ff", "#5f8cff", "#a76bff", "#ff77d2"],
    bg: "#07070f",
    eye: "#a9f7ff",
    ball: "#f2fbff",
    shape: "gem",
    radius: 0.2,
    geometry: "blocks",
    distortion: "none",
    gradient: "spectrum",
    finder: "deco",
    timing: "solid",
    alignment: "ring",
    accentMark: "none",
    mass: 0.93,
    gap: 0.04,
    strength: 0.64,
  }),
  d({
    id: "digital-glass",
    name: "Digital Glass",
    category: "Neon",
    blurb: "Translucent cyan glass modules with brighter cores.",
    stops: ["#7fe9ff", "#3f7fe0"],
    bg: "#04101a",
    eye: "#a9f2ff",
    ball: "#eafaff",
    shape: "squircle",
    radius: 0.4,
    geometry: "components",
    distortion: "none",
    gradient: "radial",
    finder: "ringed",
    timing: "pill",
    alignment: "pill",
    accentMark: "ring",
    accent: "#d8f7ff",
    accentFreq: 0.07,
    mass: 0.91,
    gap: 0.05,
    strength: 0.62,
  }),

  /* ---------------- Pastel ---------------- */
  d({
    id: "rose-gold",
    name: "Rose Gold",
    category: "Pastel",
    blurb: "Blush → copper gradient modules on warm cream.",
    stops: ["#c2705a", "#e0a08a"],
    ramp: ["#b05f4c", "#d98b74", "#e8b39c"],
    bg: "#fdf3ee",
    eye: "#a85a46",
    ball: "#a85a46",
    shape: "rounded",
    radius: 0.36,
    geometry: "single",
    distortion: "none",
    gradient: "diagonal",
    finder: "soft",
    timing: "pill",
    alignment: "pill",
    accentMark: "fleck",
    accent: "#e7c3b2",
    accentFreq: 0.08,
    mass: 0.94,
    gap: 0.05,
    strength: 0.5,
  }),
  d({
    id: "candy-hearts",
    name: "Candy Hearts",
    category: "Pastel",
    blurb: "Heart modules on a solid ink plate — playful, still full mass.",
    stops: ["#e0356b", "#ff6f9c"],
    bg: "#fff1f4",
    eye: "#c21f52",
    ball: "#c21f52",
    accent: "#ff9db8",
    shape: "heart",
    radius: 0.3,
    geometry: "single",
    distortion: "jitter",
    gradient: "linear-x",
    finder: "circle",
    timing: "dot",
    alignment: "dot",
    accentMark: "fleck",
    accentFreq: 0.1,
    mass: 0.95,
    gap: 0.04,
    strength: 0.56,
  }),
  d({
    id: "sakura",
    name: "Sakura",
    category: "Pastel",
    blurb: "Petal clusters on cream with floral finder geometry.",
    stops: ["#e07aa4", "#c2568a"],
    bg: "#fdf4f1",
    eye: "#b8477c",
    ball: "#b8477c",
    accent: "#f2c1d4",
    shape: "petal",
    radius: 0.5,
    geometry: "components",
    distortion: "wobble",
    gradient: "linear-y",
    finder: "floral",
    timing: "dot",
    alignment: "dot",
    accentMark: "fleck",
    accentFreq: 0.09,
    mass: 0.92,
    gap: 0.05,
    minSeparation: 0.56,
    strength: 0.58,
  }),
  d({
    id: "lavender-dream",
    name: "Lavender Dream",
    category: "Pastel",
    blurb: "Purple → pink soft modules, generous spacing, symmetric.",
    stops: ["#8a63d6", "#d76ba8"],
    ramp: ["#7b58cc", "#a86fd0", "#d76ba8"],
    bg: "#f8f4ff",
    eye: "#6a4bc0",
    ball: "#6a4bc0",
    shape: "squircle",
    radius: 0.44,
    geometry: "single",
    distortion: "none",
    gradient: "linear-x",
    finder: "circle",
    timing: "pill",
    alignment: "pill",
    accentMark: "none",
    mass: 0.93,
    gap: 0.08,
    minSeparation: 0.5,
    strength: 0.5,
  }),
  d({
    id: "peach-sorbet",
    name: "Peach Sorbet",
    category: "Pastel",
    blurb: "Peach, coral and pink capsules in small clusters.",
    stops: ["#e8703f", "#f0a06a"],
    ramp: ["#dd5f45", "#f08a5c", "#f6b489"],
    bg: "#fff4e8",
    eye: "#c9552f",
    ball: "#c9552f",
    shape: "capsule",
    radius: 0.48,
    geometry: "components",
    distortion: "wobble",
    gradient: "diagonal",
    finder: "solid",
    timing: "pill",
    alignment: "pill",
    accentMark: "none",
    mass: 0.93,
    gap: 0.05,
    minSeparation: 0.56,
    strength: 0.56,
  }),
  d({
    id: "strawberry-cream",
    name: "Strawberry Cream",
    category: "Pastel",
    blurb: "Strawberry-red rounded squares, clean and playful.",
    stops: ["#c8203f", "#e8556f"],
    bg: "#fff2f0",
    eye: "#a81a33",
    ball: "#a81a33",
    accent: "#f0a8b4",
    shape: "rounded",
    radius: 0.26,
    geometry: "blocks",
    distortion: "none",
    gradient: "linear-y",
    finder: "solid",
    timing: "solid",
    alignment: "solid",
    accentMark: "fleck",
    accentFreq: 0.07,
    mass: 0.96,
    gap: 0.04,
    strength: 0.48,
  }),
  d({
    id: "blueberry-milk",
    name: "Blueberry Milk",
    category: "Pastel",
    blurb: "Deep blue and violet soft clusters on pale milk blue.",
    stops: ["#2f3fa8", "#5f4fc8"],
    bg: "#eef3ff",
    eye: "#242f7f",
    ball: "#242f7f",
    shape: "squircle",
    radius: 0.42,
    geometry: "components",
    distortion: "wobble",
    gradient: "linear-y",
    finder: "circle",
    timing: "pill",
    alignment: "pill",
    accentMark: "none",
    mass: 0.94,
    gap: 0.05,
    strength: 0.54,
  }),

  /* ---------------- Retro ---------------- */
  d({
    id: "pixel-art",
    name: "Pixel Art",
    category: "Retro",
    blurb: "2×2 / 3×3 pixel tiles, hard squares, zero gradients.",
    stops: ["#1b2430", "#3d5a80"],
    bg: "#f2ede1",
    eye: "#10161f",
    ball: "#10161f",
    accent: "#e07a3f",
    shape: "square",
    radius: 0,
    geometry: "blocks",
    distortion: "steps",
    gradient: "none",
    finder: "solid",
    timing: "solid",
    alignment: "solid",
    accentMark: "fleck",
    accentFreq: 0.08,
    mass: 0.98,
    gap: 0.02,
    strength: 0.44,
  }),
  d({
    id: "8bit-neon",
    name: "8-Bit Neon",
    category: "Retro",
    blurb: "Retro game UI: hard pixel blocks in green, blue and purple.",
    stops: ["#5cff8f", "#4dc9ff"],
    ramp: ["#5cff8f", "#4dc9ff", "#b56bff"],
    bg: "#05060a",
    eye: "#8affb0",
    ball: "#eaffe0",
    shape: "square",
    radius: 0.04,
    geometry: "blocks",
    distortion: "none",
    gradient: "ramp",
    finder: "bracket",
    timing: "solid",
    alignment: "solid",
    accentMark: "tick",
    accent: "#ffe14d",
    accentFreq: 0.07,
    mass: 0.97,
    gap: 0.03,
    strength: 0.58,
  }),
  d({
    id: "arcade",
    name: "Arcade",
    category: "Retro",
    blurb: "Cabinet sprites: yellow/red rectangular groups on navy.",
    stops: ["#ffd400", "#ff3b30"],
    bg: "#0b1030",
    eye: "#ffd400",
    ball: "#fff3b0",
    accent: "#ff3b30",
    shape: "square",
    radius: 0.1,
    geometry: "runs-both",
    distortion: "steps",
    gradient: "split",
    finder: "solid",
    timing: "solid",
    alignment: "solid",
    accentMark: "spark",
    accentFreq: 0.1,
    mass: 0.96,
    gap: 0.04,
    strength: 0.62,
  }),
  d({
    id: "retro-computer",
    name: "Retro Computer",
    category: "Retro",
    blurb: "CRT phosphor green with a horizontal scan rhythm.",
    stops: ["#33ff77", "#0fa648"],
    bg: "#020a04",
    eye: "#66ff99",
    ball: "#dcffe6",
    shape: "hbar",
    radius: 0.18,
    geometry: "runs-h",
    distortion: "bands",
    gradient: "linear-y",
    finder: "bracket",
    timing: "solid",
    alignment: "solid",
    accentMark: "none",
    mass: 0.94,
    gap: 0.05,
    strength: 0.6,
  }),

  /* ---------------- World ---------------- */
  d({
    id: "bauhaus",
    name: "Bauhaus",
    category: "World",
    blurb: "Primary-colour geometric composition, hard squares.",
    stops: ["#111111", "#d32c1e"],
    ramp: ["#111111", "#d32c1e", "#f2b705", "#1f4fa3"],
    bg: "#f4efe2",
    eye: "#111111",
    ball: "#d32c1e",
    shape: "square",
    radius: 0,
    geometry: "blocks",
    distortion: "none",
    gradient: "split",
    finder: "solid",
    timing: "solid",
    alignment: "solid",
    accentMark: "none",
    mass: 0.98,
    gap: 0.04,
    strength: 0.5,
  }),
  d({
    id: "art-deco",
    name: "Art Deco",
    category: "World",
    blurb: "Gold on black: diamond modules, framed finders, corner ticks.",
    stops: ["#d4af37", "#f0d786"],
    bg: "#0d0b07",
    eye: "#e8c766",
    ball: "#fff2c4",
    accent: "#f7e7b4",
    shape: "diamond",
    radius: 0.08,
    geometry: "single",
    distortion: "none",
    gradient: "linear-y",
    finder: "deco",
    timing: "pill",
    alignment: "ring",
    accentMark: "tick",
    accentFreq: 0.1,
    mass: 0.94,
    gap: 0.01,
    strength: 0.58,
  }),
  d({
    id: "minimalist-swiss",
    name: "Minimalist Swiss",
    category: "World",
    blurb: "White ground, black modules, one restrained red accent.",
    stops: ["#111111", "#1a1a1a"],
    bg: "#ffffff",
    eye: "#111111",
    ball: "#111111",
    accent: "#e02020",
    shape: "square",
    radius: 0,
    geometry: "single",
    distortion: "none",
    gradient: "none",
    finder: "solid",
    timing: "solid",
    alignment: "solid",
    accentMark: "fleck",
    accentFreq: 0.05,
    mass: 1,
    gap: 0.02,
    strength: 0.3,
  }),
  d({
    id: "japanese-ink",
    name: "Japanese Ink",
    category: "World",
    blurb: "Sumi-e charcoal on paper, brush-rounded module edges.",
    stops: ["#1d1c1a", "#3a3833"],
    bg: "#f6f1e6",
    eye: "#141312",
    ball: "#141312",
    shape: "pebble",
    radius: 0.4,
    geometry: "components",
    distortion: "wobble",
    gradient: "none",
    finder: "solid",
    timing: "pill",
    alignment: "dot",
    accentMark: "none",
    mass: 0.94,
    gap: 0.04,
    strength: 0.52,
  }),
  d({
    id: "ukiyo-e",
    name: "Ukiyo-e",
    category: "World",
    blurb: "Woodblock indigo, vermilion and cream in large clusters.",
    stops: ["#2b3a67", "#b03a2e"],
    ramp: ["#22305c", "#4a5a8c", "#b03a2e"],
    bg: "#f3ead7",
    eye: "#22305c",
    ball: "#b03a2e",
    shape: "square",
    radius: 0.14,
    geometry: "blocks",
    distortion: "steps",
    gradient: "split",
    finder: "halo",
    timing: "solid",
    alignment: "solid",
    accentMark: "none",
    mass: 0.96,
    gap: 0.05,
    strength: 0.54,
  }),
  d({
    id: "islamic-geometry",
    name: "Islamic Geometry",
    category: "World",
    blurb: "Gold star geometry on deep emerald, pattern around the finders.",
    stops: ["#e3c567", "#c9a227"],
    bg: "#06231f",
    eye: "#f0d98a",
    ball: "#fff6d6",
    accent: "#7fd6c0",
    shape: "star",
    radius: 0,
    geometry: "single",
    distortion: "none",
    gradient: "radial",
    finder: "deco",
    timing: "pill",
    alignment: "ring",
    accentMark: "ring",
    accentFreq: 0.08,
    mass: 0.95,
    gap: 0.03,
    strength: 0.56,
  }),
  d({
    id: "moroccan-tile",
    name: "Moroccan Tile",
    category: "World",
    blurb: "Turquoise, cobalt and gold in repeating tile rhythm.",
    stops: ["#1fb6c1", "#1d4ed8"],
    ramp: ["#2fd0c5", "#1d7fd8", "#e0b23c"],
    bg: "#06202c",
    eye: "#4fe0d0",
    ball: "#f2e2b0",
    shape: "hex",
    radius: 0.1,
    geometry: "blocks",
    distortion: "none",
    gradient: "diagonal",
    finder: "cut",
    timing: "solid",
    alignment: "ring",
    accentMark: "fleck",
    accent: "#e0b23c",
    accentFreq: 0.08,
    mass: 0.94,
    gap: 0.05,
    strength: 0.6,
  }),
  d({
    id: "persian-miniature",
    name: "Persian Miniature",
    category: "World",
    blurb: "Navy, turquoise, red and gold — floral geometry around the data.",
    stops: ["#e0a83c", "#c2452f"],
    ramp: ["#f0c860", "#e0a83c", "#c2452f"],
    bg: "#0a1a3c",
    eye: "#f0c860",
    ball: "#fff0cc",
    accent: "#4fd6c8",
    shape: "petal",
    radius: 0.44,
    geometry: "single",
    distortion: "none",
    gradient: "radial",
    finder: "deco",
    timing: "dot",
    alignment: "ring",
    accentMark: "ring",
    accentFreq: 0.09,
    mass: 0.94,
    gap: 0.04,
    strength: 0.58,
  }),
  d({
    id: "gothic",
    name: "Gothic",
    category: "World",
    blurb: "Cathedral angles: crimson and silver on charcoal.",
    stops: ["#c21f3a", "#b9c0c9"],
    bg: "#0c0b0d",
    eye: "#d8dde3",
    ball: "#f0f3f6",
    accent: "#8e9aa8",
    shape: "diamond",
    radius: 0,
    geometry: "runs-v",
    distortion: "taper",
    gradient: "linear-y",
    finder: "cut",
    timing: "solid",
    alignment: "solid",
    accentMark: "tick",
    accentFreq: 0.08,
    mass: 0.95,
    gap: 0.03,
    strength: 0.6,
  }),
  d({
    id: "luxury-marble",
    name: "Luxury Marble",
    category: "World",
    blurb: "Black and gold on cream with flowing marble banding.",
    stops: ["#1b1b1b", "#2e2a24"],
    bg: "#f7f3ea",
    eye: "#141414",
    ball: "#b08d3f",
    accent: "#c9a227",
    shape: "fluid",
    radius: 0.36,
    geometry: "components",
    distortion: "bands",
    gradient: "bands",
    finder: "soft",
    timing: "pill",
    alignment: "pill",
    accentMark: "fleck",
    accentFreq: 0.07,
    mass: 0.95,
    gap: 0.03,
    minSeparation: 0.56,
    strength: 0.52,
  }),

  /* ---------------- Cosmic ---------------- */
  d({
    id: "galaxy",
    name: "Galaxy",
    category: "Cosmic",
    blurb: "Blue, violet and pink star clusters on deep navy.",
    stops: ["#7aa2ff", "#c86bff"],
    ramp: ["#6fa8ff", "#a878ff", "#ff8ad4"],
    bg: "#05060f",
    eye: "#a9c4ff",
    ball: "#f0f4ff",
    accent: "#ffe9a8",
    shape: "star",
    radius: 0.2,
    geometry: "components",
    distortion: "jitter",
    gradient: "radial",
    finder: "soft",
    timing: "pill",
    alignment: "ring",
    accentMark: "spark",
    accentFreq: 0.07,
    mass: 0.93,
    gap: 0.04,
    strength: 0.68,
  }),
  d({
    id: "nebula",
    name: "Nebula",
    category: "Cosmic",
    blurb: "Soft purple/cyan/pink regions — clouds, not micro texture.",
    stops: ["#a06bff", "#4fd8e8"],
    ramp: ["#7f5cff", "#c86bd8", "#4fd8e8", "#ff8ad4"],
    bg: "#07051a",
    eye: "#c9a9ff",
    ball: "#f2e9ff",
    shape: "bubbles",
    radius: 0.5,
    geometry: "components",
    distortion: "wobble",
    gradient: "diagonal",
    finder: "halo",
    timing: "dot",
    alignment: "dot",
    accentMark: "none",
    mass: 0.92,
    gap: 0.04,
    strength: 0.7,
  }),
  d({
    id: "solar-system",
    name: "Solar System",
    category: "Cosmic",
    blurb: "Golden orbs and circular clusters on deep black.",
    stops: ["#ffc247", "#ff8c1a"],
    bg: "#04040a",
    eye: "#ffd98a",
    ball: "#fff3d6",
    accent: "#8ab4ff",
    shape: "dots",
    radius: 0.5,
    geometry: "components",
    distortion: "none",
    gradient: "radial",
    finder: "soft",
    timing: "dot",
    alignment: "ring",
    accentMark: "ring",
    accentFreq: 0.06,
    mass: 0.94,
    gap: 0.04,
    strength: 0.62,
  }),
  d({
    id: "moonlight",
    name: "Moonlight",
    category: "Cosmic",
    blurb: "Silver-white rounded geometry on midnight blue.",
    stops: ["#e8eefc", "#b9c8e8"],
    bg: "#0b1230",
    eye: "#f2f6ff",
    ball: "#ffffff",
    shape: "rounded",
    radius: 0.38,
    geometry: "single",
    distortion: "none",
    gradient: "linear-y",
    finder: "circle",
    timing: "pill",
    alignment: "pill",
    accentMark: "none",
    mass: 0.95,
    gap: 0.05,
    strength: 0.5,
  }),
  d({
    id: "rainbow-prism",
    name: "Rainbow Prism",
    category: "Cosmic",
    blurb: "Full spectrum by position, luminance held constant.",
    stops: ["#ff4d4d", "#4d79ff"],
    ramp: ["#ff4d4d", "#ffa64d", "#ffe14d", "#5cd65c", "#4dc9ff", "#7a5cff", "#d94dff"],
    bg: "#0a0a0f",
    eye: "#f2f2f7",
    ball: "#ffffff",
    shape: "squircle",
    radius: 0.34,
    geometry: "blocks",
    distortion: "none",
    gradient: "spectrum",
    finder: "solid",
    timing: "solid",
    alignment: "solid",
    accentMark: "none",
    mass: 0.93,
    gap: 0.04,
    strength: 0.66,
    minSeparation: 0.5,
  }),

  /* ---------------- Nature ---------------- */
  d({
    id: "botanical-garden",
    name: "Botanical Garden",
    category: "Nature",
    blurb: "Leaf clusters in dark green, sage and mint.",
    stops: ["#2f6b3a", "#4f9a5a"],
    ramp: ["#1f4d2a", "#3f8a4a", "#7fc48a"],
    bg: "#f0f6ee",
    eye: "#1c4526",
    ball: "#1c4526",
    accent: "#a8d8b0",
    shape: "leaf",
    radius: 0.5,
    geometry: "components",
    distortion: "wobble",
    gradient: "linear-y",
    finder: "halo",
    timing: "pill",
    alignment: "dot",
    accentMark: "fleck",
    accentFreq: 0.08,
    mass: 0.93,
    gap: 0.05,
    strength: 0.56,
  }),
  d({
    id: "ocean-coral",
    name: "Ocean Coral",
    category: "Nature",
    blurb: "Turquoise pebbles with coral accents on deep navy.",
    stops: ["#2fd6c8", "#ff7a5c"],
    bg: "#062033",
    eye: "#7ff0e4",
    ball: "#e6fffb",
    accent: "#ff9a7a",
    shape: "pebble",
    radius: 0.44,
    geometry: "components",
    distortion: "wobble",
    gradient: "radial",
    finder: "soft",
    timing: "pill",
    alignment: "ring",
    accentMark: "fleck",
    accentFreq: 0.1,
    mass: 0.92,
    gap: 0.05,
    strength: 0.64,
  }),
  d({
    id: "tropical",
    name: "Tropical",
    category: "Nature",
    blurb: "Emerald, turquoise, yellow and coral leaf clusters.",
    stops: ["#1fa36b", "#e0a52a"],
    ramp: ["#12866b", "#2fd0a0", "#e8c33c", "#ff7a5c"],
    bg: "#f7f4e8",
    eye: "#0f6b4a",
    ball: "#0f6b4a",
    shape: "leaf",
    radius: 0.46,
    geometry: "components",
    distortion: "wobble",
    gradient: "diagonal",
    finder: "halo",
    timing: "pill",
    alignment: "dot",
    accentMark: "none",
    mass: 0.93,
    gap: 0.05,
    strength: 0.6,
  }),
  d({
    id: "fire",
    name: "Fire",
    category: "Nature",
    blurb: "Yellow → orange → red, elongating toward the edges.",
    stops: ["#ffe14d", "#ff3b1f"],
    ramp: ["#fff07a", "#ffa62e", "#ff5722", "#d81b1b"],
    bg: "#0d0503",
    eye: "#ffb703",
    ball: "#fff3c4",
    shape: "capsule",
    radius: 0.5,
    geometry: "runs-v",
    distortion: "taper",
    gradient: "linear-y",
    finder: "solid",
    timing: "pill",
    alignment: "solid",
    accentMark: "spark",
    accent: "#ffe14d",
    accentFreq: 0.06,
    mass: 0.93,
    gap: 0.04,
    strength: 0.7,
  }),
  d({
    id: "ice",
    name: "Ice",
    category: "Nature",
    blurb: "Crystalline angular shards in cyan on pale ice blue.",
    stops: ["#1f7fb8", "#3fa9d8"],
    bg: "#eef7fc",
    eye: "#14608c",
    ball: "#14608c",
    accent: "#a8dcf0",
    shape: "facet",
    radius: 0.06,
    geometry: "blocks",
    distortion: "jitter",
    gradient: "linear-x",
    finder: "cut",
    timing: "solid",
    alignment: "solid",
    accentMark: "fleck",
    accentFreq: 0.07,
    mass: 0.95,
    gap: 0.03,
    strength: 0.5,
  }),
  d({
    id: "crystal",
    name: "Crystal",
    category: "Nature",
    blurb: "Faceted gemstones with angular finders and cool gradients.",
    stops: ["#6fd8e8", "#8a7fe0"],
    ramp: ["#a9f0f7", "#6fd8e8", "#8a7fe0"],
    bg: "#0a1420",
    eye: "#c9f4ff",
    ball: "#f0fbff",
    shape: "gem",
    radius: 0.1,
    geometry: "components",
    distortion: "jitter",
    gradient: "diagonal",
    finder: "cut",
    timing: "pill",
    alignment: "ring",
    accentMark: "spark",
    accent: "#e8fbff",
    accentFreq: 0.06,
    mass: 0.94,
    gap: 0.04,
    strength: 0.62,
  }),
  d({
    id: "flower-field",
    name: "Flower Field",
    category: "Nature",
    blurb: "Pink, purple, yellow and green petals in a floral composition.",
    stops: ["#d64f8a", "#8a5cd6"],
    ramp: ["#e86fa0", "#b56fd6", "#e0b23c", "#4fa86b"],
    bg: "#fdf6f2",
    eye: "#b03a72",
    ball: "#b03a72",
    accent: "#f2c8dc",
    shape: "petal",
    radius: 0.5,
    geometry: "components",
    distortion: "wobble",
    gradient: "spectrum",
    finder: "floral",
    timing: "dot",
    alignment: "dot",
    accentMark: "fleck",
    accentFreq: 0.09,
    mass: 0.92,
    gap: 0.05,
    strength: 0.6,
  }),
  d({
    id: "topographic",
    name: "Topographic",
    category: "Nature",
    blurb: "Contour bands in green, blue and brown over a readable matrix.",
    stops: ["#2f6b4a", "#3f6f9a"],
    ramp: ["#3f7a4a", "#4a7fa8", "#8a6a44", "#2f5a3f"],
    bg: "#f3efe4",
    eye: "#24513a",
    ball: "#24513a",
    shape: "capsule",
    radius: 0.48,
    geometry: "runs-h",
    distortion: "bands",
    gradient: "bands",
    finder: "solid",
    timing: "pill",
    alignment: "pill",
    accentMark: "tick",
    accent: "#a8875a",
    accentFreq: 0.06,
    mass: 0.93,
    gap: 0.05,
    strength: 0.58,
  }),
  d({
    id: "organic-pebbles",
    name: "Organic Pebbles",
    category: "Nature",
    blurb: "Rounded pebble modules, varied by position, constant mass.",
    stops: ["#3d5a4a", "#6b8f7a"],
    bg: "#f2f0e6",
    eye: "#2c4437",
    ball: "#2c4437",
    accent: "#c2b49a",
    shape: "pebble",
    radius: 0.5,
    geometry: "single",
    distortion: "jitter",
    gradient: "linear-y",
    finder: "halo",
    timing: "pill",
    alignment: "dot",
    accentMark: "none",
    mass: 0.95,
    gap: 0.04,
    strength: 0.5,
  }),

  /* ---------------- Templates (platform kits, logo-ready) ----------------
   * Brand-flavoured kits in the spirit of template galleries like
   * qrcode-ai: platform palette + a proven camera-safe geometry recipe
   * (measured finder styles, 0.5 luminance separation floor, no distortion).
   * Each preset ships with imageMode "logo" so an uploaded brand mark lands
   * in the reserved centre plate; the QR itself never embeds trademark art.
   */
  d({
    id: "tmpl-instagram",
    name: "Instagram",
    category: "Templates",
    blurb: "Magenta-violet gradient, soft rounded modules, halo eyes.",
    stops: ["#8a3ab9", "#d6246e"],
    bg: "#ffffff",
    eye: "#8a3ab9",
    ball: "#d6246e",
    shape: "rounded",
    radius: 0.38,
    geometry: "single",
    distortion: "none",
    gradient: "diagonal",
    finder: "halo",
    timing: "pill",
    accentMark: "none",
    mass: 0.93,
    gap: 0.05,
    strength: 0.45,
    minSeparation: 0.5,
  }),
  d({
    id: "tmpl-youtube",
    name: "YouTube",
    category: "Templates",
    blurb: "Broadcast red ground with clean white rounded modules.",
    stops: ["#ffffff", "#f4f4f4"],
    bg: "#cc0000",
    eye: "#ffffff",
    ball: "#ffffff",
    shape: "rounded",
    radius: 0.3,
    geometry: "single",
    distortion: "none",
    gradient: "none",
    finder: "soft",
    timing: "pill",
    accentMark: "none",
    mass: 0.93,
    gap: 0.05,
    strength: 0.45,
    minSeparation: 0.5,
  }),
  d({
    id: "tmpl-facebook",
    name: "Facebook",
    category: "Templates",
    blurb: "Feed blue with white modules and circular eyes.",
    stops: ["#ffffff", "#e8f1ff"],
    bg: "#08417f",
    eye: "#ffffff",
    ball: "#ffffff",
    shape: "rounded",
    radius: 0.3,
    geometry: "single",
    distortion: "none",
    gradient: "linear-y",
    finder: "circle",
    timing: "pill",
    accentMark: "none",
    mass: 0.93,
    gap: 0.05,
    strength: 0.45,
    minSeparation: 0.5,
  }),
  d({
    id: "tmpl-whatsapp",
    name: "WhatsApp",
    category: "Templates",
    blurb: "Chat green on paper white with soft square eyes.",
    stops: ["#0c7a3a", "#12994a"],
    bg: "#ffffff",
    eye: "#0c7a3a",
    ball: "#0c7a3a",
    shape: "rounded",
    radius: 0.32,
    geometry: "single",
    distortion: "none",
    gradient: "linear-y",
    finder: "soft",
    timing: "pill",
    accentMark: "none",
    mass: 0.93,
    gap: 0.05,
    strength: 0.45,
    minSeparation: 0.5,
  }),
  d({
    id: "tmpl-tiktok",
    name: "TikTok",
    category: "Templates",
    blurb: "Stage black, signal white, cyan flicker accents.",
    stops: ["#f4f4f4", "#e6e6e6"],
    bg: "#010203",
    eye: "#f4f4f4",
    ball: "#f4f4f4",
    accent: "#25f4ee",
    shape: "square",
    radius: 0.08,
    geometry: "single",
    distortion: "none",
    gradient: "none",
    finder: "cut",
    timing: "solid",
    accentMark: "fleck",
    accentFreq: 0.06,
    mass: 0.94,
    gap: 0.04,
    strength: 0.45,
    minSeparation: 0.5,
  }),
  d({
    id: "tmpl-x",
    name: "X",
    category: "Templates",
    blurb: "Monochrome black-and-white, hard squares, solid eyes.",
    stops: ["#f5f5f5", "#e8e8e8"],
    bg: "#000000",
    eye: "#f5f5f5",
    ball: "#f5f5f5",
    shape: "square",
    radius: 0,
    geometry: "single",
    distortion: "none",
    gradient: "none",
    finder: "solid",
    timing: "solid",
    accentMark: "none",
    mass: 0.95,
    gap: 0.03,
    strength: 0.4,
    minSeparation: 0.5,
  }),
  d({
    id: "tmpl-twitter",
    name: "Twitter",
    category: "Templates",
    blurb: "Sky blue with white dots and circular eyes.",
    stops: ["#1d9bf0", "#1a8cd8"],
    bg: "#ffffff",
    eye: "#1d9bf0",
    ball: "#1d9bf0",
    shape: "rounded",
    radius: 0.34,
    geometry: "single",
    distortion: "none",
    gradient: "none",
    finder: "circle",
    timing: "pill",
    accentMark: "none",
    mass: 0.95,
    gap: 0.03,
    strength: 0.45,
    minSeparation: 0.5,
  }),
  d({
    id: "tmpl-telegram",
    name: "Telegram",
    category: "Templates",
    blurb: "Paper-plane blue ramp with halo eyes.",
    stops: ["#1787b5", "#2aabee"],
    bg: "#ffffff",
    eye: "#1787b5",
    ball: "#1787b5",
    shape: "rounded",
    radius: 0.3,
    geometry: "single",
    distortion: "none",
    gradient: "linear-y",
    finder: "halo",
    timing: "pill",
    accentMark: "none",
    mass: 0.93,
    gap: 0.05,
    strength: 0.45,
    minSeparation: 0.5,
  }),
  d({
    id: "tmpl-wechat",
    name: "WeChat",
    category: "Templates",
    blurb: "Message green, soft modules, quiet eyes.",
    stops: ["#0b9b0f", "#0f8a12"],
    bg: "#ffffff",
    eye: "#0b9b0f",
    ball: "#0b9b0f",
    shape: "rounded",
    radius: 0.3,
    geometry: "single",
    distortion: "none",
    gradient: "none",
    finder: "soft",
    timing: "pill",
    accentMark: "none",
    mass: 0.93,
    gap: 0.05,
    strength: 0.45,
    minSeparation: 0.5,
  }),
  d({
    id: "tmpl-linkedin",
    name: "LinkedIn",
    category: "Templates",
    blurb: "Professional blue ground, white squares, bracket eyes.",
    stops: ["#ffffff", "#eef4fb"],
    bg: "#004182",
    eye: "#ffffff",
    ball: "#ffffff",
    shape: "square",
    radius: 0.06,
    geometry: "single",
    distortion: "none",
    gradient: "none",
    finder: "bracket",
    timing: "solid",
    accentMark: "none",
    mass: 0.94,
    gap: 0.04,
    strength: 0.42,
    minSeparation: 0.5,
  }),
  d({
    id: "tmpl-google",
    name: "Google",
    category: "Templates",
    blurb: "Search blue with a green ball accent and circle eyes.",
    stops: ["#1a73e8", "#1667c9"],
    bg: "#ffffff",
    eye: "#1a73e8",
    ball: "#1e8e3e",
    shape: "rounded",
    radius: 0.32,
    geometry: "single",
    distortion: "none",
    gradient: "linear-y",
    finder: "circle",
    timing: "pill",
    accentMark: "none",
    mass: 0.93,
    gap: 0.05,
    strength: 0.45,
    minSeparation: 0.5,
  }),
  d({
    id: "tmpl-google-maps",
    name: "Google Maps",
    category: "Templates",
    blurb: "Route blue to park green with a pin-red ball.",
    stops: ["#1a73e8", "#0f9d58"],
    bg: "#ffffff",
    eye: "#1a73e8",
    ball: "#ea4335",
    shape: "rounded",
    radius: 0.3,
    geometry: "single",
    distortion: "none",
    gradient: "linear-y",
    finder: "halo",
    timing: "pill",
    accentMark: "none",
    mass: 0.93,
    gap: 0.05,
    strength: 0.45,
    minSeparation: 0.5,
  }),
  d({
    id: "tmpl-google-business",
    name: "Google Business",
    category: "Templates",
    blurb: "Storefront blue on a pale listing card.",
    stops: ["#1a73e8", "#1667c9"],
    bg: "#e8f0fe",
    eye: "#1a73e8",
    ball: "#1e8e3e",
    shape: "rounded",
    radius: 0.3,
    geometry: "single",
    distortion: "none",
    gradient: "none",
    finder: "soft",
    timing: "pill",
    accentMark: "none",
    mass: 0.93,
    gap: 0.05,
    strength: 0.45,
    minSeparation: 0.5,
  }),
  d({
    id: "tmpl-google-drive",
    name: "Google Drive",
    category: "Templates",
    blurb: "Drive blue-green diagonal with faceted eyes.",
    stops: ["#1a73e8", "#0f9d58"],
    bg: "#ffffff",
    eye: "#1a73e8",
    ball: "#0f9d58",
    shape: "square",
    radius: 0.1,
    geometry: "single",
    distortion: "none",
    gradient: "diagonal",
    finder: "cut",
    timing: "pill",
    accentMark: "none",
    mass: 0.94,
    gap: 0.04,
    strength: 0.45,
    minSeparation: 0.5,
  }),
  d({
    id: "tmpl-google-forms",
    name: "Google Forms",
    category: "Templates",
    blurb: "Forms purple ground with white soft modules.",
    stops: ["#ffffff", "#f3ecfd"],
    bg: "#7237bd",
    eye: "#ffffff",
    ball: "#ffffff",
    shape: "rounded",
    radius: 0.34,
    geometry: "single",
    distortion: "none",
    gradient: "none",
    finder: "soft",
    timing: "pill",
    accentMark: "none",
    mass: 0.93,
    gap: 0.05,
    strength: 0.45,
    minSeparation: 0.5,
  }),
  d({
    id: "tmpl-gmail",
    name: "Gmail",
    category: "Templates",
    blurb: "Envelope red ramp with halo eyes.",
    stops: ["#ea4335", "#d93025"],
    bg: "#ffffff",
    eye: "#ea4335",
    ball: "#d93025",
    shape: "rounded",
    radius: 0.3,
    geometry: "single",
    distortion: "none",
    gradient: "linear-y",
    finder: "halo",
    timing: "pill",
    accentMark: "none",
    mass: 0.93,
    gap: 0.05,
    strength: 0.45,
    minSeparation: 0.5,
  }),
  d({
    id: "tmpl-email",
    name: "Email",
    category: "Templates",
    blurb: "Inbox blue with circular eyes — the generic mail kit.",
    stops: ["#1a73e8", "#1667c9"],
    bg: "#ffffff",
    eye: "#1a73e8",
    ball: "#1a73e8",
    shape: "rounded",
    radius: 0.3,
    geometry: "single",
    distortion: "none",
    gradient: "none",
    finder: "circle",
    timing: "pill",
    accentMark: "none",
    mass: 0.93,
    gap: 0.05,
    strength: 0.45,
    minSeparation: 0.5,
  }),
  d({
    id: "tmpl-phone",
    name: "Phone Call",
    category: "Templates",
    blurb: "Call-time dots in cyan-to-blue with halo eyes.",
    stops: ["#0288b0", "#1a73e8"],
    bg: "#ffffff",
    eye: "#0288b0",
    ball: "#1a73e8",
    shape: "dots",
    radius: 0.5,
    geometry: "single",
    distortion: "none",
    gradient: "linear-y",
    finder: "halo",
    timing: "pill",
    accentMark: "none",
    mass: 0.95,
    gap: 0.04,
    strength: 0.45,
    minSeparation: 0.5,
  }),
  d({
    id: "tmpl-sms",
    name: "SMS",
    category: "Templates",
    blurb: "Bubble violet with rounded modules and halo eyes.",
    stops: ["#7c3aed", "#a855f7"],
    bg: "#ffffff",
    eye: "#7c3aed",
    ball: "#7c3aed",
    shape: "rounded",
    radius: 0.34,
    geometry: "single",
    distortion: "none",
    gradient: "linear-y",
    finder: "halo",
    timing: "pill",
    accentMark: "none",
    mass: 0.93,
    gap: 0.05,
    strength: 0.45,
    minSeparation: 0.5,
  }),
  d({
    id: "tmpl-wifi",
    name: "Wi-Fi",
    category: "Templates",
    blurb: "Hotspot yellow on router black, ring-eight eyes.",
    stops: ["#fdd835", "#fbc02d"],
    bg: "#141414",
    eye: "#fdd835",
    ball: "#fdd835",
    shape: "rounded",
    radius: 0.3,
    geometry: "single",
    distortion: "none",
    gradient: "none",
    finder: "ring8",
    timing: "pill",
    accentMark: "none",
    mass: 0.93,
    gap: 0.05,
    strength: 0.45,
    minSeparation: 0.5,
  }),
  d({
    id: "tmpl-website",
    name: "Website",
    category: "Templates",
    blurb: "Domain green-to-blue ramp with circle eyes.",
    stops: ["#0f9d58", "#1a73e8"],
    bg: "#ffffff",
    eye: "#0f9d58",
    ball: "#1a73e8",
    shape: "rounded",
    radius: 0.3,
    geometry: "single",
    distortion: "none",
    gradient: "linear-y",
    finder: "circle",
    timing: "pill",
    accentMark: "none",
    mass: 0.93,
    gap: 0.05,
    strength: 0.45,
    minSeparation: 0.5,
  }),
  d({
    id: "tmpl-paypal",
    name: "PayPal",
    category: "Templates",
    blurb: "Double-blue wallet ramp with soft eyes.",
    stops: ["#003087", "#0070ba"],
    bg: "#ffffff",
    eye: "#003087",
    ball: "#0070ba",
    shape: "rounded",
    radius: 0.32,
    geometry: "single",
    distortion: "none",
    gradient: "linear-y",
    finder: "soft",
    timing: "pill",
    accentMark: "none",
    mass: 0.93,
    gap: 0.05,
    strength: 0.45,
    minSeparation: 0.5,
  }),
  d({
    id: "tmpl-pix",
    name: "Pix",
    category: "Templates",
    blurb: "Instant-teal pixels with faceted cut eyes.",
    stops: ["#0e8f84", "#0b7a70"],
    bg: "#ffffff",
    eye: "#0e8f84",
    ball: "#0e8f84",
    shape: "square",
    radius: 0.12,
    geometry: "single",
    distortion: "none",
    gradient: "none",
    finder: "cut",
    timing: "pill",
    accentMark: "none",
    mass: 0.94,
    gap: 0.04,
    strength: 0.45,
    minSeparation: 0.5,
  }),
  d({
    id: "tmpl-payment",
    name: "Payment",
    category: "Templates",
    blurb: "Checkout amber with soft eyes — the generic pay kit.",
    stops: ["#a06a00", "#8a5c00"],
    bg: "#ffffff",
    eye: "#a06a00",
    ball: "#a06a00",
    shape: "rounded",
    radius: 0.3,
    geometry: "single",
    distortion: "none",
    gradient: "none",
    finder: "soft",
    timing: "pill",
    accentMark: "none",
    mass: 0.93,
    gap: 0.05,
    strength: 0.45,
    minSeparation: 0.5,
  }),
  d({
    id: "tmpl-spotify",
    name: "Spotify",
    category: "Templates",
    blurb: "Now-playing green on listening-room black.",
    stops: ["#1ed760", "#1db954"],
    bg: "#191414",
    eye: "#1ed760",
    ball: "#1ed760",
    shape: "rounded",
    radius: 0.34,
    geometry: "single",
    distortion: "none",
    gradient: "none",
    finder: "soft",
    timing: "pill",
    accentMark: "none",
    mass: 0.93,
    gap: 0.05,
    strength: 0.45,
    minSeparation: 0.5,
  }),
  d({
    id: "tmpl-deezer",
    name: "Deezer",
    category: "Templates",
    blurb: "Equalizer purple bars with bracket eyes.",
    stops: ["#6b21c8", "#a02fe0"],
    bg: "#ffffff",
    eye: "#6b21c8",
    ball: "#a02fe0",
    shape: "square",
    radius: 0.1,
    geometry: "runs-h",
    distortion: "none",
    gradient: "linear-y",
    finder: "bracket",
    timing: "solid",
    accentMark: "none",
    mass: 0.94,
    gap: 0.04,
    strength: 0.45,
    minSeparation: 0.5,
  }),
  d({
    id: "tmpl-soundcloud",
    name: "SoundCloud",
    category: "Templates",
    blurb: "Waveform orange capsules in horizontal runs.",
    stops: ["#ff5500", "#e64a19"],
    bg: "#ffffff",
    eye: "#ff5500",
    ball: "#ff5500",
    shape: "capsule",
    radius: 0.5,
    geometry: "runs-h",
    distortion: "none",
    gradient: "linear-x",
    finder: "soft",
    timing: "pill",
    accentMark: "none",
    mass: 0.93,
    gap: 0.05,
    strength: 0.45,
    minSeparation: 0.5,
  }),
  d({
    id: "tmpl-airbnb",
    name: "Airbnb",
    category: "Templates",
    blurb: "Bélo coral with extra-soft modules and halo eyes.",
    stops: ["#ff5a5f", "#e0484d"],
    bg: "#ffffff",
    eye: "#ff5a5f",
    ball: "#e0484d",
    shape: "rounded",
    radius: 0.4,
    geometry: "single",
    distortion: "none",
    gradient: "linear-y",
    finder: "halo",
    timing: "pill",
    accentMark: "none",
    mass: 0.93,
    gap: 0.05,
    strength: 0.45,
    minSeparation: 0.5,
  }),
  d({
    id: "tmpl-amazon",
    name: "Amazon",
    category: "Templates",
    blurb: "Parcel amber on warehouse navy.",
    stops: ["#ff9900", "#f09000"],
    bg: "#232f3e",
    eye: "#ff9900",
    ball: "#ff9900",
    shape: "rounded",
    radius: 0.3,
    geometry: "single",
    distortion: "none",
    gradient: "none",
    finder: "soft",
    timing: "pill",
    accentMark: "none",
    mass: 0.93,
    gap: 0.05,
    strength: 0.45,
    minSeparation: 0.5,
  }),
  d({
    id: "tmpl-pdf",
    name: "PDF",
    category: "Templates",
    blurb: "Document red, hard squares, bracket eyes.",
    stops: ["#e5252a", "#c01c22"],
    bg: "#ffffff",
    eye: "#e5252a",
    ball: "#c01c22",
    shape: "square",
    radius: 0.06,
    geometry: "single",
    distortion: "none",
    gradient: "none",
    finder: "bracket",
    timing: "solid",
    accentMark: "none",
    mass: 0.94,
    gap: 0.04,
    strength: 0.42,
    minSeparation: 0.5,
  }),
  d({
    id: "tmpl-vcard",
    name: "Contact Card",
    category: "Templates",
    blurb: "vCard blue with soft eyes — save-the-contact kit.",
    stops: ["#1a73e8", "#0a66c2"],
    bg: "#ffffff",
    eye: "#1a73e8",
    ball: "#0a66c2",
    shape: "rounded",
    radius: 0.3,
    geometry: "single",
    distortion: "none",
    gradient: "none",
    finder: "soft",
    timing: "pill",
    accentMark: "none",
    mass: 0.93,
    gap: 0.05,
    strength: 0.45,
    minSeparation: 0.5,
  }),
];

/* ------------------------------------------------------------------ *
 * Lookup + presets
 * ------------------------------------------------------------------ */

const BY_ID = new Map(ART_DIRECTIONS.map((dir) => [dir.id, dir]));

export function getArtDirection(id: string | undefined | null): ArtDirection | undefined {
  if (!id) return undefined;
  return BY_ID.get(id);
}

export const ART_DIRECTION_CATEGORIES: string[] = Array.from(
  new Set(ART_DIRECTIONS.map((dir) => dir.category)),
);

export const ART_DIRECTION_CATEGORY = "Styles";
/** Platform/brand template kits (logo-ready). */
export const TEMPLATE_CATEGORY = "Templates";

const inkCache = new Map<string, ResolvedInks>();

/**
 * Cached, gate-checked inks for a direction. Keyed on the required separation
 * too, because the relax ladder raises `minSeparation` — a rung that asks for
 * more contrast must actually get more contrast.
 */
export function inksFor(dir: ArtDirection): ResolvedInks {
  // Keyed on every colour-bearing field, not just the id: relax rungs and QA
  // probes clone directions with patched palettes, and a stale cache entry
  // would silently render the OLD colours (this exact bug invalidated a whole
  // round of tuning measurements before it was caught).
  const key = [
    dir.id,
    (dir.minSeparation ?? MIN_SEPARATION).toFixed(3),
    dir.bg,
    dir.stops.join(","),
    (dir.ramp ?? []).join(","),
    dir.eye ?? "",
    dir.ball ?? "",
    dir.accent ?? "",
  ].join("|");
  const hit = inkCache.get(key);
  if (hit) return hit;
  const resolved = resolveInks(dir);
  inkCache.set(key, resolved);
  return resolved;
}

/** Directions whose colour gate had to repair something — surfaced in QA. */
export function inkRepairReport(): { id: string; name: string; repairs: string[]; separation: number }[] {
  return ART_DIRECTIONS.map((dir) => {
    const inks = inksFor(dir);
    return { id: dir.id, name: dir.name, repairs: inks.repairs, separation: inks.separation };
  }).filter((row) => row.repairs.length > 0);
}

/**
 * Every direction as a studio preset. Same underlying QR matrix as everything
 * else — a direction is paint, never a different encoding.
 */
export function artDirectionPresets(): Preset[] {
  return ART_DIRECTIONS.map((dir) => {
    const inks = inksFor(dir);
    const style: QrStyle = {
      ...DEFAULT_STYLE,
      moduleShape: "square",
      eyeShape: "square",
      ballShape: "square",
      fg: inks.stops[0]!,
      bg: inks.bg,
      eyeColor: inks.eye,
      ballColor: inks.ball,
      gradientType: "none",
      gradientTo: inks.stops[inks.stops.length - 1]!,
      quietZone: Math.max(3, dir.quietZone),
      moduleGap: dir.gap,
      // Template kits reserve the centre plate for an uploaded brand mark;
      // art directions stay image-free so the artwork carries the design.
      imageMode: dir.category === "Templates" ? "logo" : "none",
      logoScale: dir.category === "Templates" ? 0.24 : DEFAULT_STYLE.logoScale,
      dotScale: 0.9,
      contrast: 0.9,
      minVersion: 5,
      ecc: "Q",
      artisticStrength: dir.strength,
      effect: "none",
      maskPattern: -1,
      artDirection: dir.id,
    };
    return {
      id: `art-${dir.id}`,
      name: dir.name,
      category: dir.category === "Templates" ? TEMPLATE_CATEGORY : ART_DIRECTION_CATEGORY,
      blurb: dir.blurb,
      style,
    };
  });
}
