import type { EyeShape } from "../types";

/**
 * Camera-battery results for the classic eye-silhouette finder system, per
 * template. Generated by `scripts/finder-battery.mjs`: every template ×
 * (frame × ball) combination rendered at 512px and decoded with the
 * non-negotiable camera variants (identity / 50% / JPEG).
 *
 * `FINDER_BATTERY[templateId]` holds one 32-bit mask per frame (in
 * FRAME_ORDER): bit i is set when BALL_ORDER[i] decodes on that template
 * under that frame. `tuneDirection` consults the table before a user's
 * eye/pupil pick reaches the renderer, so the silhouette shown is always
 * one the battery proved on THAT template — the picker can never hand the
 * code a finder the camera battery rejected.
 */
export const FRAME_ORDER = [
  "square",
  "rounded",
  "extra-rounded",
  "circle",
  "target",
  "ticks",
  "classy",
  "leaf",
  "diamond",
  "hex",
] as const;
export type FinderFrame = (typeof FRAME_ORDER)[number];

export const BALL_ORDER = [
  "square",
  "rounded",
  "extra-rounded",
  "circle",
  "classy",
  "diamond",
  "leaf",
  "hex",
] as const;
export type FinderBall = (typeof BALL_ORDER)[number];

// GENERATED by scripts/finder-battery.mjs — do not edit by hand.
// 81 templates × (frame × ball), 512px, identity+s50+jpeg.
// Bit i of mask f = BALL_ORDER[i] passes under FRAME_ORDER[f] on this template.
export const FINDER_BATTERY: Record<string, number[]> = {
  "8bit-neon": [87, 223, 223, 254, 8, 223, 223, 223, 168, 238],
  "arcade": [23, 87, 223, 204, 8, 87, 95, 222, 32, 236],
  "art-deco": [23, 87, 222, 204, 8, 0, 87, 222, 160, 232],
  "aurora-gradient": [23, 95, 223, 222, 8, 95, 95, 222, 160, 236],
  "bauhaus": [23, 95, 223, 254, 8, 95, 95, 222, 168, 236],
  "blueberry-milk": [23, 87, 223, 204, 8, 87, 87, 222, 160, 108],
  "botanical-garden": [19, 87, 94, 204, 8, 23, 87, 222, 32, 76],
  "candy-hearts": [23, 87, 222, 204, 8, 87, 87, 222, 160, 232],
  "crystal": [19, 87, 222, 204, 8, 23, 87, 222, 32, 204],
  "cyber-circuit": [23, 95, 223, 222, 8, 95, 95, 222, 160, 236],
  "cyberpunk-pink": [19, 87, 222, 204, 8, 87, 87, 222, 32, 200],
  "digital-glass": [87, 223, 223, 255, 8, 223, 223, 255, 168, 254],
  "digital-matrix": [23, 87, 223, 204, 8, 1, 87, 222, 32, 200],
  "electric-blue": [23, 87, 223, 204, 8, 23, 87, 222, 160, 108],
  "emerald-luxury": [23, 95, 223, 236, 8, 87, 95, 222, 160, 232],
  "fire": [23, 87, 223, 204, 8, 87, 87, 222, 32, 236],
  "flower-field": [23, 95, 223, 222, 8, 87, 95, 222, 160, 236],
  "galaxy": [1, 18, 4, 8, 8, 0, 18, 64, 32, 128],
  "gothic": [19, 87, 94, 200, 8, 0, 87, 220, 32, 200],
  "holographic": [23, 87, 223, 204, 8, 87, 95, 222, 160, 236],
  "ice": [19, 23, 94, 200, 8, 0, 23, 204, 32, 200],
  "islamic-geometry": [23, 95, 223, 238, 8, 87, 95, 222, 160, 232],
  "japanese-ink": [19, 23, 94, 204, 8, 87, 87, 222, 32, 76],
  "lavender-dream": [23, 87, 223, 204, 8, 87, 87, 222, 32, 236],
  "liquid-chrome": [23, 95, 223, 222, 8, 87, 95, 222, 160, 236],
  "luxury-marble": [19, 87, 94, 204, 8, 87, 95, 222, 160, 236],
  "minimalist-swiss": [23, 87, 223, 204, 8, 87, 87, 222, 32, 108],
  "moonlight": [23, 95, 223, 254, 8, 95, 223, 222, 160, 236],
  "moroccan-tile": [23, 95, 223, 222, 8, 87, 95, 222, 160, 236],
  "nebula": [23, 95, 223, 222, 8, 87, 95, 222, 160, 236],
  "neon-cyber-grid": [23, 87, 223, 204, 8, 87, 87, 222, 32, 204],
  "ocean-coral": [23, 95, 223, 254, 8, 95, 223, 222, 160, 236],
  "ocean-glass": [23, 87, 223, 204, 8, 87, 95, 222, 32, 236],
  "organic-pebbles": [23, 87, 222, 204, 8, 23, 87, 222, 32, 108],
  "peach-sorbet": [19, 23, 94, 204, 8, 23, 23, 222, 32, 204],
  "persian-miniature": [23, 87, 222, 204, 8, 87, 87, 222, 32, 200],
  "pixel-art": [23, 87, 223, 204, 8, 87, 87, 222, 32, 108],
  "rainbow-prism": [87, 223, 223, 254, 8, 223, 223, 223, 168, 236],
  "retro-computer": [23, 87, 223, 206, 8, 87, 95, 222, 160, 232],
  "rose-gold": [19, 87, 94, 204, 8, 23, 87, 222, 32, 204],
  "sakura": [23, 95, 223, 222, 8, 95, 95, 222, 168, 236],
  "solar-flare": [23, 87, 223, 204, 8, 87, 87, 222, 32, 204],
  "solar-system": [19, 23, 94, 200, 8, 0, 23, 204, 32, 200],
  "strawberry-cream": [23, 95, 223, 254, 8, 95, 95, 222, 168, 108],
  "sunset-spectrum": [19, 23, 94, 200, 8, 0, 23, 204, 32, 200],
  "synthwave-sunset": [23, 95, 223, 204, 8, 87, 95, 222, 160, 232],
  "tmpl-airbnb": [19, 87, 94, 204, 8, 87, 87, 222, 32, 236],
  "tmpl-amazon": [18, 87, 222, 200, 8, 0, 87, 222, 0, 200],
  "tmpl-deezer": [19, 87, 94, 204, 8, 23, 87, 222, 32, 204],
  "tmpl-email": [23, 87, 222, 204, 8, 87, 87, 222, 32, 232],
  "tmpl-facebook": [19, 87, 222, 200, 8, 0, 87, 222, 32, 200],
  "tmpl-gmail": [19, 87, 222, 204, 8, 87, 87, 220, 32, 104],
  "tmpl-google": [23, 95, 223, 206, 8, 87, 87, 222, 160, 232],
  "tmpl-google-business": [23, 87, 223, 204, 8, 87, 87, 206, 32, 232],
  "tmpl-google-drive": [23, 95, 223, 222, 8, 95, 95, 223, 168, 236],
  "tmpl-google-forms": [0, 95, 223, 222, 8, 95, 223, 222, 0, 236],
  "tmpl-google-maps": [23, 87, 222, 204, 8, 87, 87, 222, 32, 168],
  "tmpl-instagram": [23, 95, 223, 222, 8, 95, 95, 222, 168, 236],
  "tmpl-linkedin": [23, 95, 223, 238, 8, 95, 223, 222, 160, 236],
  "tmpl-payment": [23, 87, 222, 204, 8, 87, 87, 222, 32, 232],
  "tmpl-paypal": [19, 87, 215, 204, 8, 23, 87, 222, 32, 200],
  "tmpl-pdf": [87, 87, 223, 252, 8, 87, 95, 222, 168, 108],
  "tmpl-phone": [19, 87, 94, 204, 8, 23, 87, 222, 32, 204],
  "tmpl-pix": [23, 87, 223, 204, 8, 87, 87, 222, 32, 236],
  "tmpl-sms": [23, 95, 223, 222, 8, 95, 95, 222, 160, 236],
  "tmpl-soundcloud": [19, 87, 94, 204, 8, 23, 87, 222, 32, 204],
  "tmpl-spotify": [23, 95, 223, 254, 8, 87, 95, 222, 160, 236],
  "tmpl-telegram": [23, 87, 222, 204, 8, 87, 87, 222, 32, 232],
  "tmpl-tiktok": [23, 95, 223, 238, 8, 87, 95, 222, 160, 236],
  "tmpl-twitter": [23, 87, 223, 206, 8, 87, 87, 222, 32, 236],
  "tmpl-vcard": [19, 87, 222, 204, 8, 87, 87, 220, 32, 232],
  "tmpl-website": [19, 87, 222, 204, 8, 87, 87, 220, 32, 232],
  "tmpl-wechat": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
  "tmpl-whatsapp": [23, 87, 223, 204, 8, 87, 87, 222, 160, 108],
  "tmpl-wifi": [19, 87, 94, 200, 8, 0, 87, 222, 32, 200],
  "tmpl-x": [23, 87, 223, 204, 8, 87, 87, 222, 32, 236],
  "tmpl-youtube": [23, 87, 223, 238, 8, 87, 95, 222, 160, 232],
  "topographic": [19, 23, 94, 204, 8, 3, 87, 204, 32, 72],
  "tropical": [19, 23, 94, 204, 8, 23, 87, 222, 32, 204],
  "ukiyo-e": [19, 87, 94, 204, 8, 23, 87, 222, 160, 204],
  "vaporwave": [23, 95, 223, 254, 8, 95, 95, 222, 160, 236],
};
/**
 * The ball that passes the most templates for each frame (argmax over
 * FINDER_BATTERY). Note how far this sits from the classic default: angular
 * frames carry angular/round balls (diamond+diamond 78/81, hex+circle 79/81)
 * — diamond+square and hex+square pass on ZERO templates, which is why a
 * user's bare "diamond eye" pick resolves to a diamond ball, not a square one.
 */
export const BEST_BALL: Record<FinderFrame, FinderBall> = {
  square: "square",
  rounded: "rounded",
  "extra-rounded": "extra-rounded",
  circle: "circle",
  target: "circle",
  ticks: "square",
  classy: "rounded",
  leaf: "leaf",
  diamond: "diamond",
  hex: "circle",
};

/** Visually closest frames, in preference order, per frame. */
export const FRAME_FALLBACK: Record<FinderFrame, FinderFrame[]> = {
  square: ["rounded", "ticks", "extra-rounded", "circle"],
  rounded: ["square", "ticks", "extra-rounded"],
  "extra-rounded": ["rounded", "circle", "target", "classy"],
  circle: ["extra-rounded", "target", "rounded"],
  target: ["circle", "extra-rounded", "rounded"],
  ticks: ["rounded", "square", "extra-rounded"],
  classy: ["rounded", "leaf", "extra-rounded", "square"],
  leaf: ["classy", "rounded", "extra-rounded", "square"],
  diamond: ["hex", "square", "rounded"],
  hex: ["diamond", "square", "rounded"],
};

function toFrame(s: EyeShape): FinderFrame {
  return (FRAME_ORDER as readonly string[]).includes(s) ? (s as FinderFrame) : "square";
}
function toBall(s: EyeShape | undefined): FinderBall | undefined {
  if (s === "target") return "circle"; // same silhouette
  if (s === "ticks") return "rounded"; // same silhouette
  if (s !== undefined && (BALL_ORDER as readonly string[]).includes(s)) return s as FinderBall;
  return undefined;
}

/**
 * Resolve a user's (eye, pupil) pick to the closest (frame, ball) the camera
 * battery proved on this template. Preference order: the exact pair → the
 * frame with its best ball (the frame pick is the louder signal, 7×7 vs 3×3)
 * → the user's ball on the closest frame → the closest frame's best ball →
 * any passing frame. Returns `frame: null` when NO silhouette decodes on the
 * template (e.g. tmpl-wechat) — the caller then keeps the template's own
 * finder rather than shipping a battery-rejected one. An unknown template
 * (no battery row) trusts the pick as-is.
 */
export function safeFinder(
  templateId: string | undefined,
  frame: EyeShape,
  ball: EyeShape | undefined,
): { frame: FinderFrame | null; ball: FinderBall | undefined } {
  const f = toFrame(frame);
  const b = toBall(ball);
  const table = templateId ? FINDER_BATTERY[templateId] : undefined;
  if (!table) return { frame: f, ball: b };
  const passes = (fIdx: number, bIdx: number) => ((table[fIdx] ?? 0) & (1 << bIdx)) !== 0;
  const fi = FRAME_ORDER.indexOf(f);
  if (b !== undefined && passes(fi, BALL_ORDER.indexOf(b))) return { frame: f, ball: b };
  const best = BEST_BALL[f]!;
  if (passes(fi, BALL_ORDER.indexOf(best))) return { frame: f, ball: best };
  for (const alt of FRAME_FALLBACK[f] ?? []) {
    const ai = FRAME_ORDER.indexOf(alt);
    if (b !== undefined && passes(ai, BALL_ORDER.indexOf(b))) return { frame: alt, ball: b };
  }
  for (const alt of FRAME_FALLBACK[f] ?? []) {
    const ai = FRAME_ORDER.indexOf(alt);
    if (passes(ai, BALL_ORDER.indexOf(BEST_BALL[alt]!))) return { frame: alt, ball: BEST_BALL[alt] };
  }
  for (const alt of FRAME_FALLBACK[f] ?? []) {
    const ai = FRAME_ORDER.indexOf(alt);
    const mask = table[ai] ?? 0;
    if (mask === 0) continue;
    for (let bi = 0; bi < BALL_ORDER.length; bi++) if (mask & (1 << bi)) return { frame: alt, ball: BALL_ORDER[bi]! };
  }
  return { frame: null, ball: undefined };
}
